### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Supertroopar** [Zathrox/Explorercraft#1]
the game crashed when attacking the enderreaper here is what the crash report said
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.zathrox.explorercraft.common.entity.EnderreeperEntity.func_70097_a(EnderreeperEntity.java:349) ~[?:1.14.4-3.1.2] {re:classloading}
	at net.minecraft.entity.item.FireworkRocketEntity.func_191510_k(SourceFile:258) ~[?:?] {re:classloading}
	at net.minecraft.entity.item.FireworkRocketEntity.func_213893_k(SourceFile:194) ~[?:?] {re:classloading}
	at net.minecraft.entity.item.FireworkRocketEntity.func_213892_a(SourceFile:210) ~[?:?] {re:classloading}
	at net.minecraft.entity.item.FireworkRocketEntity.func_70071_h_(SourceFile:154) ~[?:?] {re:classloading}
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:220) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.world.ClientWorld$$Lambda$4865/1344480947.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:684) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:179) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1344) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:869) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.1.39.jar:28.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$383/1779914089.call(Unknown Source) [forge-1.14.4-28.1.39.jar:28.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.0.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.0.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.0.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.0.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.0.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.zathrox.explorercraft.common.entity.EnderreeperEntity.func_70097_a(EnderreeperEntity.java:349)
	at net.minecraft.entity.item.FireworkRocketEntity.func_191510_k(SourceFile:258)
	at net.minecraft.entity.item.FireworkRocketEntity.func_213893_k(SourceFile:194)
	at net.minecraft.entity.item.FireworkRocketEntity.func_213892_a(SourceFile:210)
	at net.minecraft.entity.item.FireworkRocketEntity.func_70071_h_(SourceFile:154)
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:220)
	at net.minecraft.client.world.ClientWorld$$Lambda$4865/1344480947.accept(Unknown Source)

-- Entity being ticked --
Details:
	Entity Type: minecraft:firework_rocket (net.minecraft.entity.item.FireworkRocketEntity)
	Entity ID: 3616
	Entity Name: Firework Rocket
	Entity's Exact location: 53.70, 59.00, -0.58
	Entity's Block location: World: (53,59,-1), Chunk: (at 5,3,15 in 3,-1; contains blocks 48,0,-16 to 63,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: -0.39, -0.00, -1.37
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:684)
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:179)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['madbomber5555'/218, l='MpServer', x=56.20, y=61.43, z=6.09]]
	Chunk stats: Client Chunk Cache: 529, 339
	Level dimension: DimensionType{minecraft:the_end}
	Level name: MpServer
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-94,63,-16), Chunk: (at 2,3,0 in -6,-1; contains blocks -96,0,-16 to -81,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 14238 game time, 14238 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:574)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1750)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$383/1779914089.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 780520552 bytes (744 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 4.0.0+61+ca3b447
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.39.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.39.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.39.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.39.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.14.4_HD_U_F4_pre7.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.14.4-28.1.39.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.39
	FML Language Providers: 
		javafml@28.1
		minecraft@1
	Mod List: 
		betteranimals-1.14.4-5.2.1.jar Cyber's Better Animal Models {betteranimals@5.2.1 DONE}
		dooglamooworlds-1.14.4-1.2.2.jar Dooglamoo Worlds {dooglamooworlds@1.14.4-1.2.2 DONE}
		Explorercraft-1.14.4-3.1.2.jar Explorercraft {explorercraft@3.1.2 DONE}
		extraboats-1.1.1-1.14.4.jar Extra Boats {extraboats@1.1.1 DONE}
		MutantBeasts-1.14.4-0.5.0.jar Mutant Beasts {mutantbeasts@1.14.4-0.5.0 DONE}
		Redstone+Gear+Mod.jar Redstone Gear Mod {redstonegearmod@1.0 DONE}
		themidnight-0.4.5.jar The Midnight {midnight@0.4.5 DONE}
		ToolBelt-1.14.4-1.12.1.jar Tool Belt {toolbelt@1.12.1 DONE}
		forge-1.14.4-28.1.39-universal.jar Forge {forge@28.1.39 DONE}
		forge-1.14.4-28.1.39-client.jar Minecraft {minecraft@1.14.4 DONE}
	Launched Version: 1.14.4-forge-28.1.39
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 431.53, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/vanilla-speculars-by-izterria-1569742692.zip, file/realistico-19-07-demo.zip (incompatible)
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz

**Comment by Zathrox** [comment]
For the interest of the report, did you shot the enderreeper with a firework?

**Comment by Supertroopar** [comment]
> For the interest of the report, did you shot the enderreeper with a firework?

yes. i also noticed this when other projectiles hit it mainly the mutant snow golem from the mutant creatures/beasts mod

**Comment by Zathrox** [comment]
> > For the interest of the report, did you shot the enderreeper with a firework?
> 
> yes. i also noticed this when other projectiles hit it mainly the mutant snow golem from the mutant creatures/beasts mod

I see, i'll test, I think I know where it's coming from, there is code to swap the entity of a ranged attack but I think a firework doesn't get counted in that, so crashes :P

**Comment by Supertroopar** [comment]
thanks for getting back to me so soon

**Comment by Zathrox** [comment]
Should be fixed in the next patch (please let me know if its not, did test but there will probably be edge cases)

**Comment by McKitten** [comment]
Similar story except no interaction (have been 1k+ away for some of the crashes) and a potion involved.
https://pastebin.com/KZkQMuzz
