### ISSUE TITLE
Game crash on loading

### ISSUE THREAD

**Issue by JadedKitteh** [Zathrox/Explorercraft#11]
I'm extremely new to using mods, and haven't any experience with coding, but am interested in learning, so any help with this issue would be wonderful! I think I installed the Explorecraft mod for 1.12 correctly, but when I launch this version, it crashes, with the following information:

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 3/5/20 8:36 PM
Description: Initializing game

java.lang.NoSuchMethodError: net.minecraftforge.common.util.EnumHelper.addHorseArmor(Ljava/lang/String;Ljava/lang/String;I)Lnet/minecraft/entity/passive/HorseArmorType;
	at zathrox.explorercraft.init.MaterialsRegistry.<clinit>(MaterialsRegistry.java:76)
	at zathrox.explorercraft.events.EventHandler.onRegisterItemsEvent(EventHandler.java:305)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_8_EventHandler_onRegisterItemsEvent_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:739)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:603)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at zathrox.explorercraft.init.MaterialsRegistry.<clinit>(MaterialsRegistry.java:76)
	at zathrox.explorercraft.events.EventHandler.onRegisterItemsEvent(EventHandler.java:305)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_8_EventHandler_onRegisterItemsEvent_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:739)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:603)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 286126208 bytes (272 MB) / 536870912 bytes (512 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.0.2529 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version             | Source                                        | Signature                                |
	|:----- |:----------------- |:------------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft         | 1.12.2              | minecraft.jar                                 | None                                     |
	| UCH   | mcp               | 9.42                | minecraft.jar                                 | None                                     |
	| UCH   | FML               | 8.0.99.99           | forge-1.12.2-14.23.0.2529.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge             | 14.23.0.2529        | forge-1.12.2-14.23.0.2529.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | mercurius_updater | 1.0                 | MercuriusUpdater-1.12.2.jar                   | None                                     |
	| UCH   | aquaculture       | 1.6.8               | Aquaculture-1.12.2-1.6.8.jar                  | None                                     |
	| UCH   | explorercraft     | 2.2.12              | Explorercraft-2.2.12.jar                      | None                                     |
	| UCH   | journeymap        | 1.12.2-5.7.0        | journeymap-1.12.2-5.7.0.jar                   | None                                     |
	| UCH   | structurize       | 1.12.2-0.10.7-ALPHA | structurize-1.12.2-0.10.7-ALPHA-universal.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 431.53' Renderer: 'GeForce GTX 1080/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.0.2529
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1080/PCIe/SSE2 GL version 4.6.0 NVIDIA 431.53, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-7820HK CPU @ 2.90GHz

**Comment by Zathrox** [comment]
not 100% sure but I think your forge is very outdated?

Latest: 14.23.5.2847
Yours: 14.23.0.2529

try updating at least to the newest recommended and let me know how it is

**Comment by JadedKitteh** [comment]
Thank you! I will give that a try!
