### ISSUE TITLE
Crashed world

### ISSUE THREAD

**Issue by HeberonYT** [Zathrox/Explorercraft#7]
**Hello, exploring with your installed mod has crashed in my world.**
Explorercraft-2.2.10.jar
1.12.2-forge1.12.2-14.23.5.2847

`Description: Exception ticking world

java.lang.NullPointerException
    at zathrox.explorercraft.world.generation.WorldGenWaterGrass.generate(WorldGenWaterGrass.java:30)
    at zathrox.explorercraft.world.WorldGenExplorer.generateOceans(WorldGenExplorer.java:198)
    at zathrox.explorercraft.world.WorldGenExplorer.generate(WorldGenExplorer.java:41)
    at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:1020)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:980)
    at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:157)
    at net.minecraft.server.management.PlayerChunkMapEntry.providePlayerChunk(PlayerChunkMapEntry.java:126)
    at net.minecraft.server.management.PlayerChunkMap.tick(PlayerChunkMap.java:226)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:227)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  Level name: world
  All players: 1 total; [EntityPlayerMP['HeberonYT'/75, l='world', x=3993.22, y=121.35, z=10784.45]]
  Chunk stats: ServerChunkCache: 574 Drop: 0
  Level seed: -130057904594197647
  Level generator: ID 00 - default, ver 1. Features enabled: true
  Level generator options: 
  Level spawn location: World: (4196,90,3575), Chunk: (at 4,5,7 in 262,223; contains blocks 4192,0,3568 to 4207,255,3583), Region: (8,6; contains chunks 256,192 to 287,223, blocks 4096,0,3072 to 4607,255,3583)
  Level time: 21110916 game time, 7016561 day time
  Level dimension: 0
  Level storage version: 0x04ABD - Anvil
  Level weather: Rain time: 173 (now: false), thunder time: 86838 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false`

**Comment by Zathrox** [comment]
Hey there, go back to 2.2.9, I recalled the 2.2.10, it seems I accidentally patched an outdated version with that world crashing bug (it only added in some new textures as a minor update) so no loss to content
