### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by dbock1989** [Zathrox/Explorercraft#9]
Hello!

Modpack: BoxyWorld
MP Version: 2.1.2
MC Version: 1.14.4
Explorercraft Version: 3.2.4

[crash-2020-01-25_21.42.58-server.txt](https://github.com/Zathrox/Explorercraft/files/4113114/crash-2020-01-25_21.42.58-server.txt)

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 1/25/20 9:42 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.zathrox.explorercraft.common.entity.EnderreeperEntity.func_70097_a(EnderreeperEntity.java:348) ~[?:1.14.4-3.2.4] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.potion.Effect.func_180793_a(Effect.java:76) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.projectile.PotionEntity.func_213888_a(SourceFile:158) ~[?:?] {re:classloading}
	at net.minecraft.entity.projectile.PotionEntity.func_70184_a(SourceFile:117) ~[?:?] {re:classloading}
	at net.minecraft.entity.projectile.ThrowableEntity.func_70071_h_(ThrowableEntity.java:137) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:587) ~[?:?] {re:classloading,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_217390_a(World.java:684) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:394) ~[?:?] {re:classloading,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:324) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.zathrox.explorercraft.common.entity.EnderreeperEntity.func_70097_a(EnderreeperEntity.java:348)
	at net.minecraft.potion.Effect.func_180793_a(Effect.java:76)
	at net.minecraft.entity.projectile.PotionEntity.func_213888_a(SourceFile:158)
	at net.minecraft.entity.projectile.PotionEntity.func_70184_a(SourceFile:117)
	at net.minecraft.entity.projectile.ThrowableEntity.func_70071_h_(ThrowableEntity.java:137)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:587)

-- Entity being ticked --
Details:
	Entity Type: minecraft:potion (net.minecraft.entity.projectile.PotionEntity)
	Entity ID: 72612
	Entity Name: Potion
	Entity's Exact location: 837.55, 19.61, 1067.54
	Entity's Block location: World: (837,19,1067), Chunk: (at 5,1,11 in 52,66; contains blocks 832,0,1056 to 847,255,1071), Region: (1,2; contains chunks 32,64 to 63,95, blocks 512,0,1024 to 1023,255,1535)
	Entity's Momentum: 0.05, 0.06, 1.33
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:684)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:394)

-- Affected level --
Details:
	All players: 4 total; [ServerPlayerEntity['ahotcraftymess'/14708, l='TheBoxyWorld 2.1.2', x=772.42, y=34.00, z=1075.88], ServerPlayerEntity['procionecurioso'/23176, l='TheBoxyWorld 2.1.2', x=206.50, y=65.00, z=-614.50], ServerPlayerEntity['Dbock1989'/571, l='TheBoxyWorld 2.1.2', x=564.35, y=26.00, z=1250.22], ServerPlayerEntity['Serial_Something'/14425, l='TheBoxyWorld 2.1.2', x=484.17, y=10.16, z=1193.39]]
	Chunk stats: ServerChunkCache: 6630
	Level dimension: DimensionType{minecraft:overworld}
	Level name: TheBoxyWorld 2.1.2
	Level seed: 4064643250896364896
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (253,72,-209), Chunk: (at 13,4,15 in 15,-14; contains blocks 240,0,-224 to 255,255,-209), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 4265462 game time, 204132 day time
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 136578 (now: false), thunder time: 77964 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:324)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3639883944 bytes (3471 MB) / 6390153216 bytes (6094 MB) up to 12832604160 bytes (12238 MB)
	CPUs: 6
	JVM Flags: 16 total; -Xms6G -Xmx12G -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=20000
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge.jar object_holder_definalize PLUGINSERVICE 
		/forge.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge.jar capability_inject_definalize PLUGINSERVICE 
		/forge.jar runtimedistcleaner PLUGINSERVICE 
		/forge.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.116
	FML Language Providers: 
		javafml@28.1
		minecraft@1
		kotlinfml@1.4.0
		kotori_scala@2.13.1

**Comment by Zathrox** [comment]
hey thanks for the post, i'll see if I can do something to the code to fix this, basically, it crashed because you threw something from the quark mod at the enderreeper, which has special teleporting properties based on if a projectile was used, i'm guessing there is some odd conflicts based on whatever you threw but I can't promise anything!

**Comment by Zathrox** [comment]
I've removed that functi
